export default 

[
    {
        id: 1,
        on: false,
        name: "Chili con carne",
        url: 'https://img.jamieoliver.com/jamieoliver/recipe-database/46258212.jpg?tr=w-800,h-1066',
        prepTime: "Preparation time: 10 mins",
        cookTime: "Cooking time: 1 hour",
        level: "Level: easy",
        ingredients: "Ingredients: ",
        ingredients1: "2 medium onions, ",
        ingredients2: "2 cloves garlic, ",
        ingredients3: "2 medium carrots, ",
        ingredients4: "2 sticks celery, ",
        ingredients5: "2 red peppers, ",
        ingredients6: "olive oil, ",
        ingredients7: "1 heaped teaspoon chilli powder, ",
        ingredients8: "1 heaped teaspoon ground cumin, ",
        ingredients9: "1 heaped teaspoon ground cinnamon, ",
        ingredients10: "1 x 400 g tin of chickpeas, ",
        ingredients11: "1 x 400 g tin of red kidney beans, ",
        ingredients12: "2 x 400 g tin of chopped tomatoes, ",
        ingredients13: "500 g quality minced beef, ",
        ingredients14: "½ a bunch of fresh coriander, ",
        ingredients15: "2 tablespoons balsamic vinegar ",
        method: "Method:" ,
        method1: "1. Peel and finely chop the onions, garlic, carrots and celery – don’t worry about the technique, just chop away until fine. Halve the red peppers, remove the stalks and seeds and roughly chop. ",
        method2: "2. Heat 2 tablespoons of oil in a large casserole pan on a medium-high heat, add the chopped veg, chilli powder, cumin, cinnamon and a good pinch of sea salt and black pepper, then cook for 7 minutes, or until softened, stirring regularly.", 
        method3: "3. Drain and add the chickpeas and kidney beans, tip in the tomatoes, breaking them up with the back of a spoon, then pour in 1 tin's worth of water. Add the minced beef, breaking any larger chunks. ",
        method4: "4. Pick the coriander leaves and put aside, then finely chop and add the stalks to the pan, with the balsamic vinegar. Season with a good pinch of sea salt and black pepper. ",
        method5: "5. Bring to the boil, then reduce the heat to low and simmer with a lid slightly ajar for 1 hour, or until slightly thickened and reduced, stirring occasionally. ",
        method6: "6. Serve up with fluffy rice or couscous, a hunk of crusty bread, or over a jacket potato, with some yoghurt, guacamole, and wedges of lime on the side for squeezing over. Sprinkle over the reserved coriander, and some fresh chilli, if you like, then tuck in. "
    },
    {
        id: 2,
        on: false,
        name: "Minestrone soup",
        url: "https://img.jamieoliver.com/jamieoliver/recipe-database/105276769.jpg?tr=w-800,h-1066",
        prepTime: "Preparation time: 30 hour" ,
        cookTime: "Cooking time: 30 hour",
        level: "Level: easy",
        ingredients: "Ingredients: ",
        ingredients1: "4 rashers of smoked streaky bacon,  ",
        ingredients2: "olive oil, ",
        ingredients3: "1 clove of garlic, ",
        ingredients4: "2 small onions, ",
        ingredients5: "2 fresh bay leaves, ",
        ingredients6: "2 carrots, ",
        ingredients7: "2 sticks of celery, ",
        ingredients8: "2 large handfuls of seasonal greens, ",
        ingredients9: "1 vegetable stock cube, ",
        ingredients10: "1 x 400 g tin of quality plum tomatoes, ",
        ingredients11: "2 x 400 g tins of beans, ",
        ingredients12: "100 g dried pasta, ",
        ingredients13: "Parmesan cheese, ",
        ingredients14: "extra virgin olive oil ",
        method: "Method:",
        method1: " 1. Put a large shallow casserole pan on a medium-high heat.",
        method2: "2. Finely slice the bacon, if using, and sprinkle into the pan with 1 tablespoon of olive oil, stirring occasionally while you prep your veg. ",
        method3: "3. Peel and finely chop the garlic and onion, adding the garlic to the pan with the bay leaves as soon as the bacon turns golden, followed by the onions. ",
        method4: "4. Trim and chop the carrots and celery into rough 1cm dice, adding to the pan as you go. Remove and finely chop any tough stalks from your greens and add to the pan. Cook for 10 to 15 minutes, stirring regularly, or until softened and caramelised. ",
        method5: "5. Crumble in the stock cube, pour in the tinned tomatoes, breaking them up with your spoon, then add 1 tin’s worth of water. ",
        method6: "6. Pour in the beans, juice and all, then add a pinch of sea salt and black pepper.", 
        method7: "7. Shred your greens and sprinkle into the pan, top up with 600ml of boiling kettle water, then add the pasta. Cover and leave to simmer for 10 to 15 minutes, or until the pasta is just cooked and the soup has thickened to your liking. ",
        method8: "8. Season the soup to perfection, then serve it with a grating of Parmesan cheese and a drizzle of extra virgin olive oil. A sprinkling of fresh baby basil leaves will always be delicious, if you’ve got them, and my kids enjoy it with a dollop of pesto on top, too. "
    },
    {
        id: 3,
        on: false,
        name: "Quickest white fish tagine",
        url: "https://img.jamieoliver.com/jamieoliver/recipe-database/109469720.jpg?tr=w-800,h-1066",
        prepTime: "Preparation time: 20 min" ,
        cookTime: "Cooking time: 15 min",
        level: "Level: easy",
        ingredients: "Ingredients: ",
        ingredients1: "150 g couscous, ",
        ingredients2: "4 cloves of garlic, ",
        ingredients3: "olive oil, ",
        ingredients4: "250 g ripe mixed-colour cherry tomatoes, ",
        ingredients5: "250 g asparagus, ",
        ingredients6: "2 heaped teaspoons rose harissa, ",
        ingredients7: "2 x 150 g white fish fillets, ",
        ingredients8: "1 lemon, ",
        ingredients9: "2 tablespoons natural yoghurt ",
        method: "Method: ",
        method1: "1. Place the couscous in a bowl, add a pinch of sea salt and black pepper, then just cover with boiling kettle water, and cover. ",
        method2: "2. Peel and slice the garlic, then place in a shallow casserole pan on a medium-high heat with 1 tablespoon of olive oil, stirring while you halve the cherry tomatoes, adding them to the pan as you go. ",
        method3: " 3. Snap the woody ends off the asparagus, roughly chop the spears and stir into the pan, then season with salt and pepper. ",
        method4: "4. Rub most of the harissa over the fish, sit it on top of the veg, finely grate over the lemon zest and squeeze over half the juice. ",
        method5: "5. Add 150ml of water, cover, and cook for 5 minutes, or until the fish is just cooked through. ",
        method6: "6. Fluff up the couscous. Ripple the remaining harissa through the yoghurt, then spoon it over the fish and couscous. Serve with lemon wedges, for squeezing over. "
    },
    {
        id: 4,
        on: false,
        name: "Quick green pasta",
        url: "https://img.jamieoliver.com/jamieoliver/recipe-database/105564455.jpg?tr=w-800,h-1066",
        prepTime: "Preparation time: 20 min" ,
        cookTime: "Cooking time: 10 min",
        level: "Level: easy",
        ingredients: "Ingredients: ",
        ingredients1: "6 spring onions, ",
        ingredients2: "1 leek, ",
        ingredients3: "1 large handful of Tenderstem broccoli spears, ",
        ingredients4: "olive oil, ",
        ingredients5: "2 cloves of garlic, ",
        ingredients6: "100 g frozen spinach, ",
        ingredients7: "2 large handfuls of frozen peas, ",
        ingredients8: "450 g dried pasta, ",
        ingredients9: "50 g Parmesan cheese ",
        method: "Method: ",
        method1: "1. Trim and slice the spring onions. Trim the leek, wash it, then finely slice. Finely slice the broccoli stalks, reserving the tips. ",
        method2: "2. Put a large pan on a medium heat. ",
        method3: "3. Put 1 tablespoon of olive oil into the pan, with the spring onions, leeks and broccoli stalks. ",
        method4: "4. Peel and finely chop the garlic and add to the pan. ",
        method5: "5. Add the frozen spinach and peas, then add a pinch of sea salt and black pepper. ",
        method6: "6. Cook for 10 to 15 minutes, or until soft and the spinach has defrosted. ",
        method7: "7. Meanwhile, cook the pasta in a large pan of boiling salted water, according to the packet instructions, adding the broccoli florets for the last 2 minutes. ",
        method8: "8. While everything is ticking away, finely grate the Parmesan. ",
        method9: "9. Scoop or pour out about 200ml of cooking water from the pasta into your veg pan. Now, you can either leave your sauce chunky, blitz it until smooth in a blender, or use a hand blender to go somewhere in between – it’s up to you. ",
        method10: "10. Drain the pasta and broccoli, and tip it into the sauce. Add 1 tablespoon of extra virgin olive oil and the grated Parmesan, and toss it all together."
    },
    {
        id: 5,
        on: false,
        name: "Classic ratatouille",
        url: "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1571_2_1437661403.jpg?tr=w-800,h-1066",
        prepTime: "Preparation time: 20 min" ,
        cookTime: "Cooking time: 1 hout 15 min",
        level: "Level: easy",
        ingredients: "Ingredients: ",
        ingredients1: "2 red onions, ",
        ingredients2: "4 cloves of garlic, ",
        ingredients3: "2 aubergines, ",
        ingredients4: "3 courgettes, ",
        ingredients5: "3 red or yellow peppers, ",
        ingredients6: "6 ripe tomatoes, ",
        ingredients7: "½ a bunch of fresh basil, ",
        ingredients8: "olive oil, ",
        ingredients9: "a few sprigs of fresh thyme, ",
        ingredients10: "1 x 400 g tin of quality plum tomatoes, ",
        ingredients11: "1 tablespoon balsamic vinegar, ",
        ingredients12: "½ a lemon ",
        method: "Method: ",
        method1: "1. Prep your ingredients before you start – peel and cut the onions into wedges, then peel and finely slice the garlic. Trim the aubergines and courgettes, deseed the peppers and chop into 2.5cm chunks. Roughly chop the tomatoes. Pick the basil leaves and set aside, then finely slice the stalks. ",
        method2: "2. Heat 2 tablespoons of oil in a large casserole pan or saucepan over a medium heat, add the chopped aubergines, courgettes and peppers (you may need to do this in batches) and fry for around 5 minutes, or until golden and softened, but not cooked through. Spoon the cooked veg into a large bowl. ",
        method3: "3. To the pan, add the onion, garlic, basil stalks and thyme leaves with another drizzle of oil, if needed. Fry for 10 to 15 minutes, or until softened and golden. ",
        method4: "4. Return the cooked veg to the pan and stir in the fresh and tinned tomatoes, the balsamic and a good pinch of sea salt and black pepper. ",
        method5: "5. Mix well, breaking up the tomatoes with the back of a spoon. Cover the pan and simmer over a low heat for 30 to 35 minutes, or until reduced, sticky and sweet. ",
        method6: "6. Tear in the basil leaves, finely grate in the lemon zest and adjust the seasoning, if needed. Serve with a hunk of bread or steamed rice. "
    },
    {
        id: 6,
        on: false,
        name: "Silky squash risotto",
        url: "https://img.jamieoliver.com/jamieoliver/recipe-database/121936025.jpg?tr=w-800,h-1066",
        prepTime: "Preparation time: 15 min" ,
        cookTime: "Cooking time: 1 hour 10 min",
        level: "Level: easy",
        ingredients: "Ingredients: ",
        ingredients1: "1 butternut (1.2kg) or acorn squash, ",
        ingredients2: "1 bunch of fresh marjoram, ",
        ingredients3: "olive oil, ",
        ingredients4: "1.2 litres quality vegetable or chicken stock, ",
        ingredients5: "1 onion, ",
        ingredients6: "1 stick of celery, ",
        ingredients7: "300 g Arborio risotto rice, ",
        ingredients8: "150 ml dry white wine, ",
        ingredients9: "200 g Tenderstem broccoli, ",
        ingredients10: "½ a lemon, ",
        ingredients11: "extra virgin olive oil, ",
        ingredients12: "50 g Parmesan cheese, ",
        ingredients13: "1 knob of unsalted butter",
        method: "Method: ",
        method1: "1. Preheat the oven to 180°C. Scrub the squash (there’s no need to peel it), deseed, then chop into 2cm chunks. ",
        method2: "2. Place the squash in a roasting tray, chop the marjoram leaves, then toss with 1 tablespoon of olive oil and a pinch of sea salt and black pepper, roast for 1 hour. ",
        method3: "3. With 20 minutes to go on the squash, simmer the stock over a low heat. Peel and chop the onion and celery, place in a pan on a medium heat with ½ a tablespoon of olive oil. Cook for 10 minutes, stirring regularly, then stir in the rice to toast for 2 minutes. ",
        method4: "4. Pour in the wine and stir until absorbed. Add a ladleful of stock and wait until it’s been fully absorbed before adding another, stirring constantly and adding ladlefuls of stock until the rice is cooked – 16 to 18 minutes. ",
        method5: "5. Remove the squash from the oven and mash up with a fork – then stir through the risotto about halfway through. ",
        method6: "6. Meanwhile, trim the broccoli, steam for 2 minutes, then toss with the lemon juice and a drizzle of extra virgin olive oil, and season to perfection. ",
        method7: "7. When the risotto is done, add enough extra stock or boiling kettle water to make the risotto oozy, then finely grate in the Parmesan, and beat in with the butter. ",
        method8: "8. Cover the pan, turn off the heat and leave to relax for 2 minutes. Stir, season to perfection. Lovely. "
    },
    {
        id: 7,
        on: false,
        name: "Super spinach pancakes",
        url: "https://img.jamieoliver.com/jamieoliver/recipe-database/92507799.jpg?tr=w-800,h-1066",
        prepTime: "Preparation time: 10 min" ,
        cookTime: "Cooking time: 20 min",
        level: "Level: easy",
        ingredients: "Ingredients: ",
        ingredients1: "1 ripe avocado, ",
        ingredients2: "350 g mixed-colour cherry tomatoes, ",
        ingredients3: "100 g baby spinach, ",
        ingredients4: "3 spring onions, ",
        ingredients5: "½ a bunch of fresh coriander, ",
        ingredients6: "1 lime, ",
        ingredients7: "extra virgin olive oil, ",
        ingredients8: "1 large free-range egg, ",
        ingredients9: "1 mug of self-raising flour, ",
        ingredients10: "1 mug of semi-skimmed milk, ",
        ingredients11: "olive oil, ",
        ingredients12: "300 g cottage cheese, ",
        ingredients13: "hot chilli sauce ",
        method: "Method: ",
        method1: "1. Halve, destone, peel and finely slice the avocado and quarter the tomatoes, then place in a salad bowl with a quarter of the spinach. ",
        method2: "2. Trim, slice and add the spring onions and pick in the coriander leaves, then squeeze over the lime juice. ",
        method3: "3. Drizzle with 1 tablespoon of extra virgin olive oil, season with sea salt and black pepper, toss to coat and put aside. ",
        method4: "4. Crack the egg into a blender, add the flour, milk, remaining spinach and a pinch of salt and pepper, then blitz until smooth. ",
        method5: "5. Place a large non stick frying pan on a medium heat, rub the pan with a little olive oil, then pour in a thin layer of batter, swirling it up and around the edges. Cook on one side only for 2 minutes, then stack up on a serving plate and repeat. ",
        method6: "6. Top each pancake with dollops of cottage cheese, the avocado salad, and a few good shakes of chilli sauce. Really nice served with extra lime wedges for squeezing over, and a fried egg on top, if you fancy. "
    },
    {
        id: 8,
        on: false,
        name: "Hot & sour chicken broth",
        url: "https://img.jamieoliver.com/jamieoliver/recipe-database/6ykh__U-KH5Bg3tceVILK3.jpg?tr=w-800,h-1066",
        prepTime: "Preparation time: 10 min" ,
        cookTime: "Cooking time: 15 min",
        level: "Level: easy",
        ingredients: "Ingredients: ",
        ingredients1: "2 shallots, ",
        ingredients2: "3 sticks of lemongrass, ",
        ingredients3: "5 cm ginger, ",
        ingredients4: "2 cloves of garlic, ",
        ingredients5: "1-2 fresh red chillies, ",
        ingredients6: "½ a bunch of fresh coriander, ",
        ingredients7: "1 bunch of spring onions, ",
        ingredients8: "2 free-range chicken breasts, ",
        ingredients9: "groundnut oil, ",
        ingredients10: "1.75 litres light organic chicken or vegetable stock, ",
        ingredients11: "fish sauce, ",
        ingredients12: "3 limes, ",
        ingredients13: "1 large handful of beansprouts ",
        method: "Method: ",
        method1: "1. Peel and dice the shallots, then remove the outer leaves from the lemongrass and chop the remainder. ",
        method2: "2. Peel and finely grate the ginger and garlic, and slice the chilli. Pick the coriander leaves, then trim and shred the spring onions and set aside. Next, cut the chicken into finger-width strips. ",
        method3: "3. Gently sweat the shallots in a splash of oil until soft. Throw in the lemongrass, ginger and garlic, and fry for 1 minute. Add the stock and most of the chilli. ",
        method4: "4. Add the chicken and simmer for about 8 minutes or until the chicken is cooked through. Add a splash of fish sauce and squeeze in the lime juice. ",
        method5: "5. Taste and add more fish sauce, lime juice or chilli as needed. At the last minute, add the coriander, beansprouts and spring onions, then divide between bowls."
    },
    {
        id: 9,
        on: false,
        name: "Perfect roast beef",
        url: "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/389_1_1436872106.jpg?tr=w-800,h-1066",
        prepTime: "Preparation time: 25 min" ,
        cookTime: "Cooking time: 1 hour 20 min",
        level: "Level: medium",
        ingredients: "Ingredients: ",
        ingredients1: "1.5 kg topside of beef, ",
        ingredients2: "2 medium onions, ",
        ingredients3: "2 carrots, ",
        ingredients4: "2 sticks celery, ",
        ingredients5: "1 bulb of garlic, ",
        ingredients6: "1 bunch of mixed fresh herbs, ",
        ingredients7: "olive oil ",
        method: "Method: ",
        method1: "1. Remove the beef from the fridge 30 minutes before you want to cook it, to let it come up to room temperature. ",
        method2: "2. Preheat the oven to 240°C. ",
        method3: "3. Wash and roughly chop the vegetables – there’s no need to peel them. Break the garlic bulb into cloves, leaving them unpeeled. ",
        method4: "4. Pile all the veg, garlic and herbs into the middle of a large roasting tray and drizzle with oil. ",
        method5: "5. Drizzle the beef with oil and season well with sea salt and black pepper, then rub all over the meat. Place the beef on top of the vegetables. ",
        method6: "6. Place the tray in the oven, then turn the heat down immediately to 200°C and cook for 1 hour for medium beef. If you prefer it medium-rare, take it out 5 to 10 minutes earlier. For well done, leave it in for another 10 to 15 minutes. ",
        method7: "7. If you’re doing roast potatoes and veggies, this is the time to crack on with them – get them into the oven for the last 45 minutes of cooking. ",
        method8: "8. Baste the beef halfway through cooking and if the veg look dry, add a splash of water to the tray to stop them from burning. ",
        method9: "9. When the beef is cooked to your liking, take the tray out of the oven and transfer the beef to a board to rest for 15 minutes or so. Cover it with a layer of tin foil and a tea towel and leave aside while you make your gravy, horseradish sauce and Yorkshire puddings."
    },
    {
        id: 10,
        on: false,
        name: "Veg & lentil cottage pie",
        url: "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1547_2_1438867071.jpg?tr=w-800,h-1066",
        prepTime: "Preparation time: 30 min" ,
        cookTime: "Cooking time: 1 hour",
        level: "Level: medium",
        ingredients: "Ingredients: ",
        ingredients1: "1 medium leek, ",
        ingredients2: "1 large carrot, ",
        ingredients3: "1 small onion, ",
        ingredients4: "1 stick celery, ",
        ingredients5: "olive oil, ",
        ingredients6: "100 g split pea red lentils, ",
        ingredients7: "500 ml organic vegetable stock, ",
        ingredients8: "100 g frozen peas, ",
        ingredients9: "sea salt, ",
        ingredients10: "freshly ground black pepper, ",
        ingredients11: "2 tablespoons tomato purée, ",
        ingredients12: "30 g Parmesan cheese, ",
        ingredients13: "300g sweet potato ",
        method: "Method: ",
        method1: "1. Preheat the oven to 180ºC/. Trim, wash and finely slice the leek. Peel and dice the carrot, onion and celery. ",
        method2: "2. Heat a splash of oil in a medium pan on a medium heat, add the leek, carrot, onion and celery. Pop the lid on and cook for 5 to 10 minutes, or until softened. Add the lentils, stock and peas, then bring to the boil, stirring regularly. Once boiling, reduce to a simmer and cook for 10 to 15 minutes, or until the lentils are cooked through. ",
        method3: "3. Season to taste with sea salt and black pepper, then add the tomato purée. Scrub the sweet potato clean, then coarsely grate it into a bowl, toss with a little oil and a good few gratings of Parmesan. ",
        method4: "4. Transfer the filling to a 15cm x 20cm ovenproof dish and sprinkle with the sweet potato. Bake for 15 to 20 minutes, or until the potato topping is golden and cooked through and the filling is piping hot."
    },
    {
        id: 11,
        on: false,
        name: "Broccoli & cheese pierogi",
        url: "https://img.jamieoliver.com/jamieoliver/recipe-database/120357257.jpg?tr=w-800,h-1066",
        prepTime: "Preparation time: 30 min" ,
        cookTime: "Cooking time: 1 hour",
        level: "Level: medium",
        ingredients: "Ingredients: ",
        ingredients1: "100 g self-raising flour, ",
        ingredients2: "1 large free-range egg, ",
        ingredients3: "1 head of broccoli, ",
        ingredients4: "25 g Cheddar cheese, ",
        ingredients5: "½ a bunch of chives, ",
        ingredients6: " 1 tablespoon soured cream, ",
        ingredients7: "2 cloves of garlic, ",
        ingredients8: "olive oil, ",
        ingredients9: "1 x 400 g tin of quality cherry tomatoes",
        method: "Method: ",
        method1: "1. Mix the flour, egg and a pinch of sea salt until you have a smooth dough, adding a splash of water- if needed. ",
        method2: "2. Knead on a flour-dusted surface for 2 minutes, then cover and pop into the fridge. ",
        method3: "3. Trim the tough end off the broccoli stalk. Remove the florets, halving any larger ones, and chop the remaining stalk into 2cm chunks. Put one third of the florets aside, then cook the rest with the chopped stalk in a pan of boiling water for 8 minutes. Drain and mash well, then finely grate in the cheese, finely chop the chives and add half, stir in the soured cream, season to perfection and leave to cool. ",
        method4: "4. Peel and slice the garlic. ",
        method5: "5. Divide the dough into eight, then roll out each piece into a 14cm circle, dusting with flour as you go. ",
        method6: "6. Divide up the filling on one side of each circle. ",
        method7: "7. Lightly brush the exposed pastry with water, then fold it over the filling, twisting along the edge to seal. ",
        method8: "8. Put a frying pan on a medium heat with ½ a tablespoon of olive oil, the pierogi and the reserved broccoli florets. Pour in 1cm of boiling kettle water, cover and boil for 4 minutes. Uncover and fry the pierogi and broccoli on one side only for 4 minutes, or until the water has evaporated and the bases are golden. ",
        method9: "9. Meanwhile, put 1 teaspoon of oil and the garlic into the pan you used to boil your broccoli, stir until lightly golden, then pour in the tomatoes, simmer for 2 minutes and season to perfection. "
    },
    {
        id: 12,
        on: false,
        name: "Mediterranean vegetable rice",
        url: "https://img.jamieoliver.com/jamieoliver/recipe-database/94741165.jpg?tr=w-800,h-1066",
        prepTime: "Preparation time: 15 min" ,
        cookTime: "Cooking time: 30 min",
        level: "Level: easy",
        ingredients: "Ingredients: ",
        ingredients1: "300 g basmati rice, ",
        ingredients2: "1 small red onion, ",
        ingredients3: "1 courgette, ",
        ingredients4: "4 ripe mixed-colour tomatoes, ",
        ingredients5: "4 tablespoons green pesto, ",
        ingredients6: "olive oil, ",
        ingredients7: "8 black olives, ",
        ingredients8: "white wine vinegar, ",
        ingredients9: "extra virgin olive oil, ",
        ingredients10: "4 sprigs of fresh basil, ",
        ingredients11: "½ x 125 g ball of mozzarella cheese ",
        method: "Method: ",
        method1: "1. Preheat the grill to high. Tip the rice into a 25cm x 35cm roasting tray, pour over 650ml of boiling salted water and cook over a medium heat for 12 minutes, stirring occasionally, then turn off the heat. ",
        method2: "2. Peel the red onion, then very finely slice with the courgette. Finely slice the tomatoes into rounds. ",
        method3: "3. Randomly bomb the pesto over the rice, then start layering up your veg: cover the rice with rounds of onion, then move on to a layer of courgettes, overlapping them as you go, followed by a layer of tomatoes. Repeat, moving slightly nearer the middle each time until you’ve covered the whole surface. ",
        method4: "4. Drizzle with 2 tablespoons of olive oil and sprinkle with black pepper, then place under the grill on the middle shelf for 25 minutes, or until beautifully gratinated. ",
        method5: "5. For the tapenade- finely chop the olives, then mix with ½ a tablespoon each of vinegar and extra virgin olive oil. ",
        method6: "6. To serve, pick over the basil leaves, dot over the olive tapenade and delicately tear over the mozzarella."
    },
    {
        id: 13,
        on: false,
        name: "Spaghetti Bolognese",
        url: "https://img.jamieoliver.com/jamieoliver/recipe-database/80307052.jpg?tr=w-800,h-1066",
        prepTime: "Preparation time: 15 min" ,
        cookTime: "Cooking time: 1 hour",
        level: "Level: easy",
        ingredients: "Ingredients: ",
        ingredients1: "2 cloves of garlic, ",
        ingredients2: "1 onion, ",
        ingredients3: "2 sprigs of fresh rosemary, ",
        ingredients4: "6 rashers smoked streaky bacon,  ",
        ingredients5: "olive oil, ",
        ingredients6: "500 g minced beef, ",
        ingredients7: "200 ml red wine, ",
        ingredients8: "1 x 280 g jar of sun-dried tomatoes, ",
        ingredients9: "2 x 400 g tins of plum tomatoes, ",
        ingredients10: "500 g dried spaghetti, ",
        ingredients11: "Parmesan cheese, ",
        ingredients12: "extra virgin olive oil",
        method: "Method: ",
        method1: "1. Preheat the oven to 180ºC. ",
        method2: "2. Peel and finely chop the garlic and onions, pick and finely chop the rosemary, then finely slice the bacon. ",
        method3: "3. Heat a splash of oil in a casserole pan on a medium heat, add the bacon, rosemary, garlic and onion and cook for 5 minutes, stirring occasionally. ",
        method4: "4. Add the minced beef, breaking it apart, then cook for 2 to 3 minutes, or until starting to brown, then pour in the wine. Leave to bubble and cook away. ",
        method5: "5. Meanwhile, drain and tip the sun-dried tomatoes into a food processor, blitz to a paste, then add to the pan with the tomatoes. Stir well, break the plum tomatoes apart a little. ",
        method6: "6. Cover with a lid then place in the oven for 1 hour, removing the lid and giving it a stir after 30 minutes – if it looks a little dry at this stage, add a splash of water to help it along. ",
        method7: "7. About 10 minutes before the time is up, cook the spaghetti in boiling salted water according to the packet instructions. ",
        method8: "8. Once the spaghetti is cooked, drain, reserving a mugful of cooking water, then return to the pan with a few spoons of Bolognese, a good grating of Parmesan and a drizzle of extra virgin olive oil. ",
        method9: "9. Toss to coat the spaghetti, loosening with a splash of cooking water, if needed. Serve, enjoy!."
    },
    {
        id: 14,
        on: false,
        name: "Classic kartoffelpuffer- potato pancakes",
        url: "https://www.daringgourmet.com/wp-content/uploads/2017/10/Kartoffelpuffer-12.jpg",
        prepTime: "Preparation time: 15 min" ,
        cookTime: "Cooking time: 10 min",
        level: "Level: easy",
        ingredients: "Ingredients: ",
        ingredients1: "6 or 7 medium starchy potatoes, ",
        ingredients2: "1 Brown onion, ",
        ingredients3: "2 Eggs, ",
        ingredients4: "1/4 cip Plain flour, ",
        ingredients5: "Butter and olive oil for frying",
        method: "Method: ",
        method1: "1. Wash and peel the potatoes. ",
        method2: "2. Grate the potatoes on the rough side of the grater and Place the grated potatoes in a large bowl. ",
        method3: "3. Peel and grate the onion and Add the grated onion to the grated potato. ",
        method4: "4. Lightly beat the 2 eggs. ",
        method5: "5. Measure out 1/3 cup of flour. ",
        method6: "6. Add the eggs, flour and salt to the bowl with the potato and onion. ",
        method7: "7. Mix together well. ",
        method8: "8. Place 1/4 cup fulls into a hot fry pan with a little olive oil and butter. Flatten them out a little bit. ",
        method9: "9. Fry for about 3-5 minutes on each side on a medium to high heat until golden. ",
        method10: "10. Drain on paper towels. "
    },
    {
        id: 15,
        on: false,
        name: "Polish ”Kopytka” – whole wheat dumplings with sauerkraut and honey. ",
        url: "https://img.jamieoliver.com/home/wp-content/uploads/features-import/2014/10/feature-header20.jpg",
        prepTime: "Preparation time: 10 min" ,
        cookTime: "Cooking time: 15 min",
        level: "Level: easy",
        ingredients: "Ingredients: ",
        ingredients1: "2 cups mashed potatoes cold, ",
        ingredients2: "1 large egg, ",
        ingredients3: "1 cup all-purpose flour",
        method: "Method: ",
        method1: "1. Place mashed potatoes in a mixing bowl. They should be cold, so this is a great way to use up leftover potatoes. ",
        method2: "2. Add egg and flour and mix until the dough comes together. Place dough onto a floured surface and divide into two parts. Roll one part of the dough into a long log and slice into 1.5 to 2 dumplings. ",
        method3: "3. In a large saucepan or pot, boil water and add 1 teaspoon of salt. Add 5 to 8 dumplings at a time to the boiling water and cook until they start to float at the top. Remove and place on a plate. Repeat with remaining dumplings. ",
        method4: "4. You can serve the dumplings right away as a side dish or follow the suggestion below. ",
        method5: "5. In a skillet, heat up 1 tablespoon of olive oil and 1 tablespoon of butter. Add cooked dumplings and cook until golden brown. Remove onto a plate. Add 2 minced garlic cloves, 1 small yellow onion, chopped, 4 slices of bacon,chopped, and 4 white mushrooms, washed, sliced. Saute until fragrant and the bacon is crispy. Toss with dumplings and serve."
    },
    {
        id: 16,
        on: false,
        name: "Spicy 'nduja vongole",
        url: "https://img.jamieoliver.com/jamieoliver/recipe-database/64975493.jpg?tr=w-800,h-1066",
        prepTime: "Preparation time: 10 min" ,
        cookTime: "Cooking time: 15 min",
        level: "Level: easy",
        ingredients: "Ingredients: ",
        ingredients1: "150 g dried linguine, ",
        ingredients2: "500 g clams- scrubbed, ",
        ingredients3: "20 g higher-welfare ’nduja, ",
        ingredients4: "½ a bunch of fresh flat-leaf parsley, ",
        ingredients5: "100 ml light rosé wine",
        method: "Method: ",
        method1: "1. Cook the pasta in a pan of boiling salted water according to the packet instructions, draining 1 minute early and reserving a mugful of cooking water. ",
        method2: "2. Meanwhile, sort through the clams. ",
        method3: "3. Tear the ’nduja into a large cold non-stick frying pan, add 1 tablespoon of olive oil, place on a medium heat and let the ’nduja melt while you finely chop the parsley. ",
        method4: "4. Stir most of the parsley into the ’nduja pan with the clams and rosé, and put the lid on. ",
        method5: "5. After 3 or 4 minutes the clams will start to open – keep jiggling the pan until they’ve all opened, then remove from the heat, discarding any unopened clams. ",
        method6: "6. Toss the drained pasta into the clam pan with a splash of reserved cooking water and simmer for 1 minute. Taste and season to perfection with sea salt and black pepper, if needed. ",
        method7: "7. Dish up, drizzle with a little extra virgin olive oil and scatter over the remaining parsley, and tuck in."
    },
];